version: "3.9"

services:
  bot:
    build: .
    container_name: sardoba-review-bot_app
    env_file: .env
    command: ["python", "-m", "app.main"]
    restart: unless-stopped
    environment:
      TZ: ${TZ}